CoreDict={
".lnx":"hatari",
".gbc":"gambatte",
".gba":"mednafen_gba",
".gen":"genesis_plus_gx",
".ngc":"mednafen_ngp",
".ngp":"mednafen_ngp",
".nes":"bnes",
".nds":"desmume",
".vb":"mednafen_vb",
".pce":"mednafen_pce_fast",
".iso":"pcsx_rearmed",
".snes":"bsnes_balanced",
".smc":"bsnes_balanced"
}