# -*- coding: utf-8 -*-
Channels=[
{'url': 'http://onelike.tv/match-arena.html', 'img': 'http://onelike.tv/images/matcharena.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/cartoon-network.html', 'img': 'http://onelike.tv/images/cartoon_network.png', 'title': 'Cartoon Network #2'},
{'url': 'http://onelike.tv/match-boets.html', 'img': 'http://onelike.tv/images/matchboets.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\x91\xd0\xbe\xd0\xb5\xd1\x86 #2'},
{'url': 'http://onelike.tv/ren-tv.html', 'img': 'http://onelike.tv/images/ren.png', 'title': '\xd0\xa0\xd0\x95\xd0\x9d \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/tnt4.html', 'img': 'http://onelike.tv/images/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24 #2'},
{'url': 'http://onelike.tv/tnt.html', 'img': 'http://onelike.tv/images/tnt.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 #2'},
{'url': 'http://onelike.tv/sts.html', 'img': 'http://onelike.tv/images/sts.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 #2'},
{'url': 'http://onelike.tv/novyj-kanal.html', 'img': 'http://onelike.tv/images/novij.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/muz-tv.html', 'img': 'http://onelike.tv/images/muztv.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/stb.html', 'img': 'http://onelike.tv/images/stb.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91 #2'},
{'url': 'http://onelike.tv/pervyj-kanal.html', 'img': 'http://onelike.tv/images/pervij.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/nickelodeon.html', 'img': 'http://onelike.tv/images/nick.png', 'title': '\xd0\x9d\xd0\xb8\xd0\xba\xd0\xb5\xd0\xbb\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbe\xd0\xbd #2'},
{'url': 'http://onelike.tv/dozhd.html', 'img': 'http://onelike.tv/images/dozhd.png', 'title': '\xd0\x94\xd0\xbe\xd0\xb6\xd0\xb4\xd1\x8c #2'},
{'url': 'http://onelike.tv/galaxy-tv.html', 'img': 'http://onelike.tv/images/galaxy.png', 'title': 'Galaxy TV #2'},
{'url': 'http://onelike.tv/tiji.html', 'img': 'http://onelike.tv/images/tiji.png', 'title': 'Tiji #2'},
{'url': 'http://onelike.tv/gulli.html', 'img': 'http://onelike.tv/images/gulli.png', 'title': 'Gulli #2'},
{'url': 'http://onelike.tv/radost-moya.html', 'img': 'http://onelike.tv/images/radostmoya.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f #2'},
{'url': 'http://onelike.tv/pyatnitsa.html', 'img': 'http://onelike.tv/images/pyatnitsa.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 #2'},
{'url': 'http://onelike.tv/english-club-tv.html', 'img': 'http://onelike.tv/images/engcl.png', 'title': 'English Club TV #2'},
{'url': 'http://onelike.tv/russia-1.html', 'img': 'http://onelike.tv/images/rus1.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1 #2'},
{'url': 'http://onelike.tv/ntv.html', 'img': 'http://onelike.tv/images/ntv.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/1-plus-1.html', 'img': 'http://onelike.tv/images/1plus1.png', 'title': '1+1 #2'},
{'url': 'http://onelike.tv/ictv.html', 'img': 'http://onelike.tv/images/ictv.png', 'title': 'ICTV #2'},
{'url': 'http://onelike.tv/khl-tv.html', 'img': 'http://onelike.tv/images/khl.png', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/match-tv.html', 'img': 'http://onelike.tv/images/matchtv.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/viasat-explorer.html', 'img': 'http://onelike.tv/images/via_ex.png', 'title': 'Viasat Explorer #2'},
{'url': 'http://onelike.tv/viasat-history.html', 'img': 'http://onelike.tv/images/via_his.png', 'title': 'Viasat History #2'},
{'url': 'http://onelike.tv/viasat-nature.html', 'img': 'http://onelike.tv/images/via_nat.png', 'title': 'Viasat Nature #2'},
{'url': 'http://onelike.tv/nst.html', 'img': 'http://onelike.tv/images/nst.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2 #2'},
{'url': 'http://onelike.tv/tv1000.html', 'img': 'http://onelike.tv/images/tv1000.png', 'title': '\xd0\xa2\xd0\x92 1000 #2'},
{'url': 'http://onelike.tv/tv1000-action.html', 'img': 'http://onelike.tv/images/tv1000act.png', 'title': 'TV1000 Action #2'},
{'url': 'http://onelike.tv/tv-1000-russkoe-kino.html', 'img': 'http://onelike.tv/images/tv1000rus.png', 'title': '\xd0\xa2\xd0\x92 1000 \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/tv-21-vek.html', 'img': 'http://onelike.tv/images/tv21.png', 'title': 'TV XXI #2'},
{'url': 'http://onelike.tv/illyuzion-plus.html', 'img': 'http://onelike.tv/images/iluzplus.png', 'title': '\xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #2'},
{'url': 'http://onelike.tv/zee-tv.html', 'img': 'http://onelike.tv/images/zeetv.png', 'title': 'Zee TV #2'},
{'url': 'http://onelike.tv/lifenews.html', 'img': 'http://onelike.tv/images/lifenews.png', 'title': '\xd0\x9b\xd0\xb0\xd0\xb9\xd1\x84 \xd0\x9d\xd1\x8c\xd1\x8e\xd1\x81 #2'},
{'url': 'http://onelike.tv/2x2.html', 'img': 'http://onelike.tv/images/2na2.png', 'title': '2x2 #2'},
{'url': 'http://onelike.tv/rossia-24.html', 'img': 'http://onelike.tv/images/rus24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24 #2'},
{'url': 'http://onelike.tv/multimaniya.html', 'img': 'http://onelike.tv/images/multiman.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f #2'},
{'url': 'http://onelike.tv/trk-ukraina.html', 'img': 'http://onelike.tv/images/trkukr.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/inter.html', 'img': 'http://onelike.tv/images/inter.png', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80 #2'},
{'url': 'http://onelike.tv/ru-tv.html', 'img': 'http://onelike.tv/images/rutv.png', 'title': '\xd0\xa0\xd0\xa3 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/discovery.html', 'img': 'http://onelike.tv/images/discavery.png', 'title': '\xd0\x94\xd0\xb8\xd1\x81\xd0\xba\xd0\xb0\xd0\xb2\xd0\xb5\xd1\x80\xd0\xb8 #2'},
{'url': 'http://onelike.tv/national-geographic.html', 'img': 'http://onelike.tv/images/natgeo.png', 'title': 'National Geographic #2'},
{'url': 'http://onelike.tv/animal-planet.html', 'img': 'http://onelike.tv/images/animpl.png', 'title': 'Animal Planet #2'},
{'url': 'http://onelike.tv/disney.html', 'img': 'http://onelike.tv/images/disney.png', 'title': '\xd0\x94\xd0\xb8\xd1\x81\xd0\xbd\xd0\xb5\xd0\xb9 #2'},
{'url': 'http://onelike.tv/strashnoe-hd.html', 'img': 'http://onelike.tv/images/strash.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD #2'},
{'url': 'http://onelike.tv/eurosport.html', 'img': 'http://onelike.tv/images/eurosport.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 #2'},
{'url': 'http://onelike.tv/eurosport-2.html', 'img': 'http://onelike.tv/images/eurosport2.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 #2'},
{'url': 'http://onelike.tv/tekhno-24.html', 'img': 'http://onelike.tv/images/24teh.png', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24 #2'},
{'url': 'http://onelike.tv/viasat-sport.html', 'img': 'http://onelike.tv/images/viasatsport.png', 'title': '\xd0\x92\xd0\xb8\xd0\xb0\xd1\x81\xd0\xb0\xd1\x82 \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 #2'},
{'url': 'http://onelike.tv/ostrosyuzhetnoe-hd.html', 'img': 'http://onelike.tv/images/ostrotv.png', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD #2'},
{'url': 'http://onelike.tv/1hd.html', 'img': 'http://onelike.tv/images/1hd.png', 'title': '1HD #2'},
{'url': 'http://onelike.tv/mega-tv.html', 'img': 'http://onelike.tv/images/mega.png', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/tet.html', 'img': 'http://onelike.tv/images/tet.png', 'title': '\xd0\xa2\xd0\x95\xd0\xa2 #2'},
{'url': 'http://onelike.tv/nlo-tv.html', 'img': 'http://onelike.tv/images/nlotv.png', 'title': '\xd0\x9d\xd0\x9b\xd0\x9e \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/mult.html', 'img': 'http://onelike.tv/images/mult.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82 #2'},
{'url': 'http://onelike.tv/qtv.html', 'img': 'http://onelike.tv/images/qtv.png', 'title': 'QTV #2'},
{'url': 'http://onelike.tv/pik-tv.html', 'img': 'http://onelike.tv/images/piktv.png', 'title': '\xd0\x9f\xd0\x98\xd0\x9a \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/russian-music-box.html', 'img': 'http://onelike.tv/images/rusmusic.png', 'title': 'Russian Music Box #2'},
{'url': 'http://onelike.tv/112-kanal.html', 'img': 'http://onelike.tv/images/112ua.png', 'title': '112 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/rbk.html', 'img': 'http://onelike.tv/images/rbk.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a #2'},
{'url': 'http://onelike.tv/semejnoe-hd.html', 'img': 'http://onelike.tv/images/semyatv.png', 'title': '\xd0\xa1\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xb9\xd0\xbd\xd0\xbe\xd0\xb5 HD #2'},
{'url': 'http://onelike.tv/oruzhie.html', 'img': 'http://onelike.tv/images/oruzie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5 #2'},
{'url': 'http://onelike.tv/otr.html', 'img': 'http://onelike.tv/images/otr.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0 #2'},
{'url': 'http://onelike.tv/kanal-chjo.html', 'img': 'http://onelike.tv/images/kanalchjo.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa7\xd1\x91 #2'},
{'url': 'http://onelike.tv/you-tv.html', 'img': 'http://onelike.tv/images/youtv.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xae #2'},
{'url': 'http://onelike.tv/nauka-2.html', 'img': 'http://onelike.tv/images/nauka2.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2 #2'},
{'url': 'http://onelike.tv/futbol-1-ua.html', 'img': 'http://onelike.tv/images/futukr1.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/futbol-2-ua.html', 'img': 'http://onelike.tv/images/futukr2.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/sts-love.html', 'img': 'http://onelike.tv/images/stslove.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love #2'},
{'url': 'http://onelike.tv/domashnij.html', 'img': 'http://onelike.tv/images/domash.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9 #2'},
{'url': 'http://onelike.tv/komediya-tv.html', 'img': 'http://onelike.tv/images/komediatv.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/2-plus-2.html', 'img': 'http://onelike.tv/images/2plus2.png', 'title': '2+2 #2'},
{'url': 'http://onelike.tv/istoriya.html', 'img': 'http://onelike.tv/images/istoriya.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f #2'},
{'url': 'http://onelike.tv/history-channel.html', 'img': 'http://onelike.tv/images/history.png', 'title': 'History #2'},
{'url': 'http://onelike.tv/tv3.html', 'img': 'http://onelike.tv/images/tv3.png', 'title': '\xd0\xa2\xd0\x923 #2'},
{'url': 'http://onelike.tv/euronews.html', 'img': 'http://onelike.tv/images/euronews.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbd\xd1\x8c\xd1\x8e\xd1\x81 #2'},
{'url': 'http://onelike.tv/5-kanal-ukraina.html', 'img': 'http://onelike.tv/images/5ua.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/europa-plus-tv.html', 'img': 'http://onelike.tv/images/eurplus.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb0 \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/mtv-rossiya.html', 'img': 'http://onelike.tv/images/mtvru.png', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f #2'},
{'url': 'http://onelike.tv/sky-bundesliga-1.html', 'img': 'http://onelike.tv/images/skybundesliga.png', 'title': 'Sky Bundesliga 1 #2'},
{'url': 'http://onelike.tv/k1.html', 'img': 'http://onelike.tv/images/k1.png', 'title': '\xd0\x9a1 #2'},
{'url': 'http://onelike.tv/k2.html', 'img': 'http://onelike.tv/images/k2.png', 'title': '\xd0\x9a2 #2'},
{'url': 'http://onelike.tv/tv1000-megahit-hd.html', 'img': 'http://onelike.tv/images/megahit.png', 'title': 'TV1000 Megahit HD #2'},
{'url': 'http://onelike.tv/tv1000-comedy-hd.html', 'img': 'http://onelike.tv/images/tv1000comedy.png', 'title': 'TV1000 Comedy HD #2'},
{'url': 'http://onelike.tv/tv1000-premium-hd.html', 'img': 'http://onelike.tv/images/tv1000premium.png', 'title': 'TV1000 Premium HD #2'},
{'url': 'http://onelike.tv/karusel.html', 'img': 'http://onelike.tv/images/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c #2'},
{'url': 'http://onelike.tv/sport-1-ukraina.html', 'img': 'http://onelike.tv/images/sport1ukr.png', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/sport-2-ukraina.html', 'img': 'http://onelike.tv/images/sport2ukr.png', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/setanta-sports.html', 'img': 'http://onelike.tv/images/setantasports.png', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0 \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 #2'},
{'url': 'http://onelike.tv/ntn.html', 'img': 'http://onelike.tv/images/ntn.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d #2'},
{'url': 'http://onelike.tv/5-kanal-russia.html', 'img': 'http://onelike.tv/images/5kanalrus.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f #2'},
{'url': 'http://onelike.tv/moya-planeta.html', 'img': 'http://onelike.tv/images/moyaplaneta.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #2'},
{'url': 'http://onelike.tv/zvezda.html', 'img': 'http://onelike.tv/images/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0 #2'},
{'url': 'http://onelike.tv/amedia-1.html', 'img': 'http://onelike.tv/images/amedia1.png', 'title': 'Amedia 1 #2'},
{'url': 'http://onelike.tv/amedia-2.html', 'img': 'http://onelike.tv/images/amedia2.png', 'title': 'Amedia 2 #2'},
{'url': 'http://onelike.tv/amedia-premium-hd.html', 'img': 'http://onelike.tv/images/amediahd.png', 'title': 'Amedia Premium HD #2'},
{'url': 'http://onelike.tv/sovershenno-sekretno.html', 'img': 'http://onelike.tv/images/sovsek.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/russkij-illyuzion.html', 'img': 'http://onelike.tv/images/ruillyuzion.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd #2'},
{'url': 'http://onelike.tv/tvc.html', 'img': 'http://onelike.tv/images/tvc.png', 'title': '\xd0\xa2\xd0\x92\xd0\xa6 #2'},
{'url': 'http://onelike.tv/rtr-planeta.html', 'img': 'http://onelike.tv/images/rtrplaneta.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #2'},
{'url': 'http://onelike.tv/paramount-comedy.html', 'img': 'http://onelike.tv/images/paramount.png', 'title': 'Paramount Comedy #2'},
{'url': 'http://onelike.tv/ria-novosti.html', 'img': 'http://onelike.tv/images/ria.png', 'title': '\xd0\xa0\xd0\x98\xd0\x90 \xd0\x9d\xd0\xbe\xd0\xb2\xd0\xbe\xd1\x81\xd1\x82\xd0\xb8 #2'},
{'url': 'http://onelike.tv/moskva-24.html', 'img': 'http://onelike.tv/images/moskva24.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24 #2'},
{'url': 'http://onelike.tv/24-ukraina.html', 'img': 'http://onelike.tv/images/24ukraina.png', 'title': '24 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #2'},
{'url': 'http://onelike.tv/espreso-tv.html', 'img': 'http://onelike.tv/images/espreso.png', 'title': '\xd0\x95\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/bigudi.html', 'img': 'http://onelike.tv/images/bigudi.png', 'title': '\xd0\x91\xd0\xb8\xd0\xb3\xd1\x83\xd0\xb4\xd0\xb8 #2'},
{'url': 'http://onelike.tv/detskij-kanal.html', 'img': 'http://onelike.tv/images/detskij.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/avto-24.html', 'img': 'http://onelike.tv/images/avto24.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24 #2'},
{'url': 'http://onelike.tv/avtoplyus.html', 'img': 'http://onelike.tv/images/avtoplyus.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #2'},
{'url': 'http://onelike.tv/mir.html', 'img': 'http://onelike.tv/images/mir.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9c\xd0\xb8\xd1\x80 #2'},
{'url': 'http://onelike.tv/lya-minor.html', 'img': 'http://onelike.tv/images/lyaminor.png', 'title': '\xd0\x9b\xd1\x8f-\xd0\xbc\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80 #2'},
{'url': 'http://onelike.tv/shanson-tv.html', 'img': 'http://onelike.tv/images/shanson.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/mezzo.html', 'img': 'http://onelike.tv/images/mezzo.png', 'title': 'Mezzo #2'},
{'url': 'http://onelike.tv/dom-kino.html', 'img': 'http://onelike.tv/images/domkino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/boomerang.html', 'img': 'http://onelike.tv/images/boomerang.png', 'title': '\xd0\x91\xd1\x83\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb3 #2'},
{'url': 'http://onelike.tv/malyatko-tv.html', 'img': 'http://onelike.tv/images/malyatko.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8f\xd1\x82\xd0\xba\xd0\xbe \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/bridge-tv.html', 'img': 'http://onelike.tv/images/bridge.png', 'title': '\xd0\x91\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb6 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/russkij-bestseller.html', 'img': 'http://onelike.tv/images/rubestseller.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80 #2'},
{'url': 'http://onelike.tv/russkij-roman.html', 'img': 'http://onelike.tv/images/ruroman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd #2'},
{'url': 'http://onelike.tv/russkij-detektiv.html', 'img': 'http://onelike.tv/images/rudetektiv.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2 #2'},
{'url': 'http://onelike.tv/russia-today.html', 'img': 'http://onelike.tv/images/rustoday.png', 'title': 'Russia Today #2'},
{'url': 'http://onelike.tv/kuhnya-tv.html', 'img': 'http://onelike.tv/images/kuhnyatv.png', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/muzhskoj-kanal.html', 'img': 'http://onelike.tv/images/muzhskoj.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/8-kanal.html', 'img': 'http://onelike.tv/images/8kanal.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #2'},
{'url': 'http://onelike.tv/okhota-i-rybalka.html', 'img': 'http://onelike.tv/images/ohryb.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0 #2'},
{'url': 'http://onelike.tv/kazsport.html', 'img': 'http://onelike.tv/images/kazsport.png', 'title': '\xd0\x9a\xd0\x90\xd0\x97\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 #2'},
{'url': 'http://onelike.tv/belarus-5.html', 'img': 'http://onelike.tv/images/belarus5.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5 #2'},
{'url': 'http://onelike.tv/kino-tv.html', 'img': 'http://onelike.tv/images/kinotv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/ua-pervyj.html', 'img': 'http://onelike.tv/images/uapervyj.png', 'title': 'UA \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 #2'},
{'url': 'http://onelike.tv/11-kanal.html', 'img': 'http://onelike.tv/images/11kanal.png', 'title': '11 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb (\xd0\x94\xd0\xbd\xd0\xb5\xd0\xbf\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba) #2'},
{'url': 'http://onelike.tv/news-one.html', 'img': 'http://onelike.tv/images/newsone.png', 'title': 'News One #2'},
{'url': 'http://onelike.tv/evrokino.html', 'img': 'http://onelike.tv/images/evrokino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/boks-tv.html', 'img': 'http://onelike.tv/images/bokstv.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/24-dok.html', 'img': 'http://onelike.tv/images/24dok.png', 'title': '24 \xd0\x94\xd0\xbe\xd0\xba #2'},
{'url': 'http://onelike.tv/indiya-tv.html', 'img': 'http://onelike.tv/images/indiyatv.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/nano-tv.html', 'img': 'http://onelike.tv/images/nanotv.png', 'title': '\xd0\x9d\xd0\xb0\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/feniks-plyus-kino.html', 'img': 'http://onelike.tv/images/feniks.png', 'title': '\xd0\xa4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xba\xd1\x81 \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/telekanal-futbol.html', 'img': 'http://onelike.tv/images/telekanalfutbol.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb #2'},
{'url': 'http://onelike.tv/tonis.html', 'img': 'http://onelike.tv/images/tonis.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x81 #2'},
{'url': 'http://onelike.tv/rossiya-kultura.html', 'img': 'http://onelike.tv/images/rossiyakultura.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0 #2'},
{'url': 'http://onelike.tv/okhotnik-i-rybolov.html', 'img': 'http://onelike.tv/images/okhotnikrybolov.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 #2'},
{'url': 'http://onelike.tv/russkij-ekstrim.html', 'img': 'http://onelike.tv/images/russkijekstrim.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x8d\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc #2'},
{'url': 'http://onelike.tv/mgm.html', 'img': 'http://onelike.tv/images/mgm.png', 'title': 'MGM #2'},
{'url': 'http://onelike.tv/eda-tv.html', 'img': 'http://onelike.tv/images/edatv.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/tlc.html', 'img': 'http://onelike.tv/images/tlc.png', 'title': 'TLC #2'},
{'url': 'http://onelike.tv/muzhskoe-kino.html', 'img': 'http://onelike.tv/images/muzhskoekino.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #2'},
{'url': 'http://onelike.tv/365-dnej.html', 'img': 'http://onelike.tv/images/365dnej.png', 'title': '365 \xd0\x94\xd0\xbd\xd0\xb5\xd0\xb9 #2'},
{'url': 'http://onelike.tv/mnogo-tv.html', 'img': 'http://onelike.tv/images/mnogotv.png', 'title': '\xd0\x9c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xa2\xd0\x92 #2'},
{'url': 'http://onelike.tv/plyusplyus.html', 'img': 'http://onelike.tv/images/plyusplyus.png', 'title': '\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #2'},
{'url': 'http://onelike.tv/kanal-m1.html', 'img': 'http://onelike.tv/images/kanalm1.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9c1 #2'},
{'url': 'http://onelike.tv/kanal-m2.html', 'img': 'http://onelike.tv/images/kanalm2.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x9c2 #2'},
{'url': 'http://onelike.tv/voprosy-i-otvety.html', 'img': 'http://onelike.tv/images/voprosyotvety.png', 'title': '\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd1\x8b \xd0\xb8 \xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd1\x8b #2'},
]
