# -*- coding: utf-8 -*-
Channels=[
{'url': 'http://www.glaz.tv/online-tv/tnt', 'img': 'http://www.glaz.tv/images/logos/tv/tnt.gif', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 #7'},
{'url': 'http://www.glaz.tv/online-tv/sts', 'img': 'http://www.glaz.tv/images/logos/tv/sts.gif', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 #7'},
{'url': 'http://www.glaz.tv/online-tv/ren-tv', 'img': 'http://www.glaz.tv/images/logos/tv/ren-tv.gif', 'title': '\xd0\xa0\xd0\xb5\xd0\xbd \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/rossiya-1', 'img': 'http://www.glaz.tv/images/logos/tv/rossiya-1.gif', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1 #7'},
{'url': 'http://www.glaz.tv/online-tv/ntv', 'img': 'http://www.glaz.tv/images/logos/tv/ntv.gif', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/comedy-tv', 'img': 'http://www.glaz.tv/images/logos/tv/comedy-tv.gif', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24 #7'},
{'url': 'http://www.glaz.tv/online-tv/rossiya-24', 'img': 'http://www.glaz.tv/images/logos/tv/rossiya-24.gif', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24 #7'},
{'url': 'http://www.glaz.tv/online-tv/perec', 'img': 'http://www.glaz.tv/images/logos/tv/perec.gif', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd1\x86 #7'},
{'url': 'http://www.glaz.tv/online-tv/tv-3', 'img': 'http://www.glaz.tv/images/logos/tv/tv-3.gif', 'title': '\xd0\xa2\xd0\x923 #7'},
{'url': 'http://www.glaz.tv/online-tv/pyatyi-kanal', 'img': 'http://www.glaz.tv/images/logos/tv/pyatyi-kanal.gif', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #7'},
{'url': 'http://www.glaz.tv/online-tv/zvezda', 'img': 'http://www.glaz.tv/images/logos/tv/zvezda.gif', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/dom-kino', 'img': 'http://www.glaz.tv/images/logos/tv/dom-kino.gif', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe #7'},
{'url': 'http://www.glaz.tv/online-tv/komediya-tv', 'img': 'http://www.glaz.tv/images/logos/tv/komediya-tv.gif', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/tv-centr', 'img': 'http://www.glaz.tv/images/logos/tv/tv-centr.gif', 'title': '\xd0\xa2\xd0\x92 \xd0\xa6\xd0\xb5\xd0\xbd\xd1\x82\xd1\x80 (\xd0\xa2\xd0\x92\xd0\xa6) #7'},
{'url': 'http://www.glaz.tv/online-tv/russkoe-kino', 'img': 'http://www.glaz.tv/images/logos/tv/russkoe-kino.gif', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #7'},
{'url': 'http://www.glaz.tv/online-tv/nst', 'img': 'http://www.glaz.tv/images/logos/tv/nst.gif', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2 #7'},
{'url': 'http://www.glaz.tv/online-tv/pyatnica', 'img': 'http://www.glaz.tv/images/logos/tv/pyatnica.gif', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/tv-xxi', 'img': 'http://www.glaz.tv/images/logos/tv/tv-xxi.gif', 'title': 'TV XXI (TV21) #7'},
{'url': 'http://www.glaz.tv/online-tv/domashniy', 'img': 'http://www.glaz.tv/images/logos/tv/domashniy.gif', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/disney-channel', 'img': 'http://www.glaz.tv/images/logos/tv/disney-channel.gif', 'title': 'Disney Channel #7'},
{'url': 'http://www.glaz.tv/online-tv/24-tehno', 'img': 'http://www.glaz.tv/images/logos/tv/24-tehno.gif', 'title': '\xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe 24 #7'},
{'url': 'http://www.glaz.tv/online-tv/sony-sci-fi', 'img': 'http://www.glaz.tv/images/logos/tv/sony-sci-fi.gif', 'title': 'Sony Sci-Fi #7'},
{'url': 'http://www.glaz.tv/online-tv/sovershenno-sekretno', 'img': 'http://www.glaz.tv/images/logos/tv/sovershenno-sekretno.gif', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe #7'},
{'url': 'http://www.glaz.tv/online-tv/inter', 'img': 'http://www.glaz.tv/images/logos/tv/inter.gif', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80 #7'},
{'url': 'http://www.glaz.tv/online-tv/nickelodeon', 'img': 'http://www.glaz.tv/images/logos/tv/nickelodeon.gif', 'title': 'Nickelodeon #7'},
{'url': 'http://www.glaz.tv/online-tv/rtr-planeta', 'img': 'http://www.glaz.tv/images/logos/tv/rtr-planeta.gif', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/ru-tv', 'img': 'http://www.glaz.tv/images/logos/tv/ru-tv.gif', 'title': 'RU TV #7'},
{'url': 'http://www.glaz.tv/online-tv/ohotnik-i-rybolov', 'img': 'http://www.glaz.tv/images/logos/tv/ohotnik-i-rybolov.gif', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 #7'},
{'url': 'http://www.glaz.tv/online-tv/evropa-plus-tv', 'img': 'http://www.glaz.tv/images/logos/tv/evropa-plus-tv.gif', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb0 \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/muz-tv', 'img': 'http://www.glaz.tv/images/logos/tv/muz-tv.gif', 'title': '\xd0\x9c\xd1\x83\xd0\xb7-\xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/life-news', 'img': 'http://www.glaz.tv/images/logos/tv/life-news.gif', 'title': 'LIFE #7'},
{'url': 'http://www.glaz.tv/online-tv/moya-planeta', 'img': 'http://www.glaz.tv/images/logos/tv/moya-planeta.gif', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/2x2', 'img': 'http://www.glaz.tv/images/logos/tv/2x2.gif', 'title': '2\xd1\x852 #7'},
{'url': 'http://www.glaz.tv/online-tv/cartoon-network', 'img': 'http://www.glaz.tv/images/logos/tv/cartoon-network.gif', 'title': 'Cartoon Network #7'},
{'url': 'http://www.glaz.tv/online-tv/paramount-comedy', 'img': 'http://www.glaz.tv/images/logos/tv/paramount-comedy.gif', 'title': 'Paramount Comedy #7'},
{'url': 'http://www.glaz.tv/online-tv/karusel', 'img': 'http://www.glaz.tv/images/logos/tv/karusel.gif', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c #7'},
{'url': 'http://www.glaz.tv/online-tv/set', 'img': 'http://www.glaz.tv/images/logos/tv/set.gif', 'title': 'SET (Sony TV) #7'},
{'url': 'http://www.glaz.tv/online-tv/boec-tv', 'img': 'http://www.glaz.tv/images/logos/tv/boec-tv.gif', 'title': '\xd0\x91\xd0\xbe\xd0\xb5\xd1\x86 \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/mtv-russia', 'img': 'http://www.glaz.tv/images/logos/tv/mtv-russia.gif', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f #7'},
{'url': 'http://www.glaz.tv/online-tv/sts-love', 'img': 'http://www.glaz.tv/images/logos/tv/sts-love.gif', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love #7'},
{'url': 'http://www.glaz.tv/online-tv/sony-turbo', 'img': 'http://www.glaz.tv/images/logos/tv/sony-turbo.gif', 'title': 'Sony Turbo #7'},
{'url': 'http://www.glaz.tv/online-tv/avto-plus', 'img': 'http://www.glaz.tv/images/logos/tv/avto-plus.gif', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #7'},
{'url': 'http://www.glaz.tv/online-tv/shanson-tv', 'img': 'http://www.glaz.tv/images/logos/tv/shanson-tv.gif', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/rossiya-k', 'img': 'http://www.glaz.tv/images/logos/tv/rossiya-k.gif', 'title': '\xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/24-dok', 'img': 'http://www.glaz.tv/images/logos/tv/24-dok.gif', 'title': '24 \xd0\x94\xd0\xbe\xd0\xba #7'},
{'url': 'http://www.glaz.tv/online-tv/yu-tv', 'img': 'http://www.glaz.tv/images/logos/tv/yu-tv.gif', 'title': '\xd0\xae \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/russian-music-box', 'img': 'http://www.glaz.tv/images/logos/tv/russian-music-box.gif', 'title': 'Russian Music Box #7'},
{'url': 'http://www.glaz.tv/online-tv/kuhnya-tv', 'img': 'http://www.glaz.tv/images/logos/tv/kuhnya-tv.gif', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/bridge-tv', 'img': 'http://www.glaz.tv/images/logos/tv/bridge-tv.gif', 'title': 'Bridge TV #7'},
{'url': 'http://www.glaz.tv/online-tv/5-y-kanal', 'img': 'http://www.glaz.tv/images/logos/tv/5-y-kanal.gif', 'title': '5-\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #7'},
{'url': 'http://www.glaz.tv/online-tv/che', 'img': 'http://www.glaz.tv/images/logos/tv/che.gif', 'title': '\xd0\xa7\xd0\xb5 #7'},
{'url': 'http://www.glaz.tv/online-tv/rbk', 'img': 'http://www.glaz.tv/images/logos/tv/rbk.gif', 'title': '\xd0\xa0\xd0\x91\xd0\x9a #7'},
{'url': 'http://www.glaz.tv/online-tv/ntn', 'img': 'http://www.glaz.tv/images/logos/tv/ntn.gif', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d #7'},
{'url': 'http://www.glaz.tv/online-tv/euronews-russian', 'img': 'http://www.glaz.tv/images/logos/tv/euronews-russian.gif', 'title': 'Euronews \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/detskiy-mir-teleklub', 'img': 'http://www.glaz.tv/images/logos/tv/detskiy-mir-teleklub.gif', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xbc\xd0\xb8\xd1\x80 #7'},
{'url': 'http://www.glaz.tv/online-tv/indiya-tv', 'img': 'http://www.glaz.tv/images/logos/tv/indiya-tv.gif', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/interesnoe-tv', 'img': 'http://www.glaz.tv/images/logos/tv/interesnoe-tv.gif', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80\xd0\xb5\xd1\x81\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/muzyka-pervogo', 'img': 'http://www.glaz.tv/images/logos/tv/muzyka-pervogo.gif', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe #7'},
{'url': 'http://www.glaz.tv/online-tv/khl-tv', 'img': 'http://www.glaz.tv/images/logos/tv/khl-tv.gif', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/mir', 'img': 'http://www.glaz.tv/images/logos/tv/mir.gif', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 #7'},
{'url': 'http://www.glaz.tv/online-tv/nick-jr', 'img': 'http://www.glaz.tv/images/logos/tv/nick-jr.gif', 'title': 'Nick Jr. #7'},
{'url': 'http://www.glaz.tv/online-tv/futbol', 'img': 'http://www.glaz.tv/images/logos/tv/futbol.gif', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb #7'},
{'url': 'http://www.glaz.tv/online-tv/pervyi-nacionalnyi', 'img': 'http://www.glaz.tv/images/logos/tv/pervyi-nacionalnyi.gif', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbd\xd0\xb0\xd1\x86\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/lya-minor', 'img': 'http://www.glaz.tv/images/logos/tv/lya-minor.gif', 'title': '\xd0\x9b\xd1\x8f-\xd0\x9c\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80 #7'},
{'url': 'http://www.glaz.tv/online-tv/365-dnei', 'img': 'http://www.glaz.tv/images/logos/tv/365-dnei.gif', 'title': '365 \xd0\x94\xd0\xbd\xd0\xb5\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/enter-film', 'img': 'http://www.glaz.tv/images/logos/tv/enter-film.gif', 'title': '\xd0\x95\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80 \xd1\x84\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbc #7'},
{'url': 'http://www.glaz.tv/online-tv/mega', 'img': 'http://www.glaz.tv/images/logos/tv/mega.gif', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/multimaniya', 'img': 'http://www.glaz.tv/images/logos/tv/multimaniya.gif', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f #7'},
{'url': 'http://www.glaz.tv/online-tv/moskva-24', 'img': 'http://www.glaz.tv/images/logos/tv/moskva-24.gif', 'title': '\xd0\x9c\xd0\xbe\xd1\x81\xd0\xba\xd0\xb2\xd0\xb0 24 #7'},
{'url': 'http://www.glaz.tv/online-tv/ocean-tv', 'img': 'http://www.glaz.tv/images/logos/tv/ocean-tv.gif', 'title': 'Ocean TV #7'},
{'url': 'http://www.glaz.tv/online-tv/k1', 'img': 'http://www.glaz.tv/images/logos/tv/k1.gif', 'title': '\xd0\x9a1 #7'},
{'url': 'http://www.glaz.tv/online-tv/boomerang', 'img': 'http://www.glaz.tv/images/logos/tv/boomerang.gif', 'title': 'Boomerang #7'},
{'url': 'http://www.glaz.tv/online-tv/cbs-drama', 'img': 'http://www.glaz.tv/images/logos/tv/cbs-drama.gif', 'title': 'CBS Drama #7'},
{'url': 'http://www.glaz.tv/online-tv/100-tv', 'img': 'http://www.glaz.tv/images/logos/tv/100-tv.gif', 'title': 'Life 78 (100 \xd0\xa2\xd0\x92) #7'},
{'url': 'http://www.glaz.tv/online-tv/outdoor-channel', 'img': 'http://www.glaz.tv/images/logos/tv/outdoor-channel.gif', 'title': 'Outdoor Channel #7'},
{'url': 'http://www.glaz.tv/online-tv/xsport', 'img': 'http://www.glaz.tv/images/logos/tv/xsport.gif', 'title': 'Xsport #7'},
{'url': 'http://www.glaz.tv/online-tv/a-one', 'img': 'http://www.glaz.tv/images/logos/tv/a-one.gif', 'title': 'A-One #7'},
{'url': 'http://www.glaz.tv/online-tv/radost-moya', 'img': 'http://www.glaz.tv/images/logos/tv/radost-moya.gif', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f #7'},
{'url': 'http://www.glaz.tv/online-tv/sport-2-ukraina', 'img': 'http://www.glaz.tv/images/logos/tv/sport-2-ukraina.gif', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 (\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0) #7'},
{'url': 'http://www.glaz.tv/online-tv/pervyi-obrazovatelniy', 'img': 'http://www.glaz.tv/images/logos/tv/pervyi-obrazovatelniy.gif', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/spas', 'img': 'http://www.glaz.tv/images/logos/tv/spas.gif', 'title': '\xd0\xa1\xd0\x9f\xd0\x90\xd0\xa1 #7'},
{'url': 'http://www.glaz.tv/online-tv/cnn-international', 'img': 'http://www.glaz.tv/images/logos/tv/cnn-international.gif', 'title': 'CNN International #7'},
{'url': 'http://www.glaz.tv/online-tv/soyuz', 'img': 'http://www.glaz.tv/images/logos/tv/soyuz.gif', 'title': '\xd0\xa1\xd0\xbe\xd1\x8e\xd0\xb7 #7'},
{'url': 'http://www.glaz.tv/online-tv/sport-1-ukraina', 'img': 'http://www.glaz.tv/images/logos/tv/sport-1-ukraina.gif', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 (\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0) #7'},
{'url': 'http://www.glaz.tv/online-tv/muzhskoy', 'img': 'http://www.glaz.tv/images/logos/tv/muzhskoy.gif', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/k2', 'img': 'http://www.glaz.tv/images/logos/tv/k2.gif', 'title': '\xd0\x9a2 #7'},
{'url': 'http://www.glaz.tv/online-tv/piksel-tv', 'img': 'http://www.glaz.tv/images/logos/tv/piksel-tv.gif', 'title': '\xd0\x9f\xd0\xb8\xd0\xba\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xa2\xd0\x92 #7'},
{'url': 'http://www.glaz.tv/online-tv/mama-tv', 'img': 'http://www.glaz.tv/images/logos/tv/mama-tv.gif', 'title': '\xd0\x9c\xd0\xb0\xd0\xbc\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/world-fashion-channel-russia', 'img': 'http://www.glaz.tv/images/logos/tv/world-fashion-channel-russia.gif', 'title': 'World Fashion Channel Russia #7'},
{'url': 'http://www.glaz.tv/online-tv/pervyi-avtomobilnyi', 'img': 'http://www.glaz.tv/images/logos/tv/pervyi-avtomobilnyi.gif', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb1\xd0\xb8\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 #7'},
{'url': 'http://www.glaz.tv/online-tv/tdk', 'img': 'http://www.glaz.tv/images/logos/tv/tdk.gif', 'title': '\xd0\xa2\xd0\x94\xd0\x9a #7'},
{'url': 'http://www.glaz.tv/online-tv/euronews', 'img': 'http://www.glaz.tv/images/logos/tv/euronews.gif', 'title': 'Euronews #7'},
{'url': 'http://www.glaz.tv/online-tv/a-one-ukraina', 'img': 'http://www.glaz.tv/images/logos/tv/a-one-ukraina.gif', 'title': 'A-One \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #7'},
{'url': 'http://www.glaz.tv/online-tv/zik', 'img': 'http://www.glaz.tv/images/logos/tv/zik.gif', 'title': 'ZIK #7'},
{'url': 'http://www.glaz.tv/online-tv/myzen-tv', 'img': 'http://www.glaz.tv/images/logos/tv/myzen-tv.gif', 'title': 'myZen.tv #7'},
]
