# -*- coding: utf-8 -*-
Channels=[
{'url': 'http://ok-tv.org/channels/1-ntv.html', 'img': 'http://ok-tv.org/images/ntv_button.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/2-tnt.html', 'img': 'http://ok-tv.org/images/tnt_button.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa2 #5'},
{'url': 'http://ok-tv.org/channels/3-sts.html', 'img': 'http://ok-tv.org/images/sts_button.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 #5'},
{'url': 'http://ok-tv.org/channels/4-pervyj-kanal.html', 'img': 'http://ok-tv.org/images/pervij_button.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/5-rossiya-1.html', 'img': 'http://ok-tv.org/images/button_rus1.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 1 #5'},
{'url': 'http://ok-tv.org/channels/6-match-tv.html', 'img': 'http://ok-tv.org/images/match.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87 \xd1\x82\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/7-sport-1.html', 'img': 'http://ok-tv.org/images/button_sport1rus.png', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 #5'},
{'url': 'http://ok-tv.org/channels/8-cartoon-network.html', 'img': 'http://ok-tv.org/images/button_cartoon.png', 'title': 'Cartoon Network #5'},
{'url': 'http://ok-tv.org/channels/9-nickelodeon.html', 'img': 'http://ok-tv.org/images/button_nick.png', 'title': 'Nickelodeon #5'},
{'url': 'http://ok-tv.org/channels/10-disney-channel.html', 'img': 'http://ok-tv.org/images/button_disney.png', 'title': 'Disney Channel #5'},
{'url': 'http://ok-tv.org/channels/11-ren-tv.html', 'img': 'http://ok-tv.org/images/button_ren.png', 'title': '\xd0\xa0\xd0\x95\xd0\x9d \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/12-tnt-comedy.html', 'img': 'http://ok-tv.org/images/tnt4.png', 'title': '\xd0\xa2\xd0\x9d\xd0\xa24 #5'},
{'url': 'http://ok-tv.org/channels/18-perets.html', 'img': 'http://ok-tv.org/images/chetv.png', 'title': '\xd0\xa7\xd0\xb5 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/19-pyatnitsa.html', 'img': 'http://ok-tv.org/images/button_patnica.png', 'title': '\xd0\x9f\xd1\x8f\xd1\x82\xd0\xbd\xd0\xb8\xd1\x86\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/20-tv-xxi.html', 'img': 'http://ok-tv.org/images/button_tv21.png', 'title': 'TV XXI #5'},
{'url': 'http://ok-tv.org/channels/21-nst.html', 'img': 'http://ok-tv.org/images/button_nst.png', 'title': '\xd0\x9d\xd0\xa1\xd0\xa2 #5'},
{'url': 'http://ok-tv.org/channels/25-paramount-comedy.html', 'img': 'http://ok-tv.org/images/pacomedy.png', 'title': 'Paramount Comedy #5'},
{'url': 'http://ok-tv.org/channels/26-viasat-explorer.html', 'img': 'http://ok-tv.org/images/explorer.png', 'title': 'Viasat Explorer #5'},
{'url': 'http://ok-tv.org/channels/27-national-geographic.html', 'img': 'http://ok-tv.org/images/national.png', 'title': 'National Geographic #5'},
{'url': 'http://ok-tv.org/channels/28-mult.html', 'img': 'http://ok-tv.org/images/mult.png', 'title': '\xd0\x9c\xd0\xa3\xd0\x9b\xd0\xac\xd0\xa2 #5'},
{'url': 'http://ok-tv.org/channels/29-discovery-science.html', 'img': 'http://ok-tv.org/images/DS.png', 'title': 'Discovery science #5'},
{'url': 'http://ok-tv.org/channels/30-discovery-channel.html', 'img': 'http://ok-tv.org/images/D.png', 'title': 'Discovery channel #5'},
{'url': 'http://ok-tv.org/channels/31-bojtsovskij-klub.html', 'img': 'http://ok-tv.org/images/Boy.png', 'title': '\xd0\x91\xd0\xbe\xd0\xb9\xd1\x86\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd0\xbb\xd1\x83\xd0\xb1 #5'},
{'url': 'http://ok-tv.org/channels/40-eurosport.html', 'img': 'http://ok-tv.org/images/eurosport.png', 'title': 'Eurosport #5'},
{'url': 'http://ok-tv.org/channels/41-ru-tv.html', 'img': 'http://ok-tv.org/images/rutv.png', 'title': 'RU TV #5'},
{'url': 'http://ok-tv.org/channels/42-oruzhie.html', 'img': 'http://ok-tv.org/images/oruzie.png', 'title': '\xd0\x9e\xd1\x80\xd1\x83\xd0\xb6\xd0\xb8\xd0\xb5 #5'},
{'url': 'http://ok-tv.org/channels/43-tv1000.html', 'img': 'http://ok-tv.org/images/tv1000.png', 'title': 'TV1000 #5'},
{'url': 'http://ok-tv.org/channels/44-tv1000-action.html', 'img': 'http://ok-tv.org/images/tv1000_act.png', 'title': 'TV1000 Action #5'},
{'url': 'http://ok-tv.org/channels/45-tv1000-russkoe-kino.html', 'img': 'http://ok-tv.org/images/tv1000_rukino.png', 'title': 'TV1000 \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/46-eurosport-2.html', 'img': 'http://ok-tv.org/images/eurosp2.png', 'title': 'Eurosport 2 #5'},
{'url': 'http://ok-tv.org/channels/47-1hd.html', 'img': 'http://ok-tv.org/images/1hdmus.png', 'title': '1HD #5'},
{'url': 'http://ok-tv.org/channels/48-zee-tv.html', 'img': 'http://ok-tv.org/images/zee.png', 'title': 'Zee TV #5'},
{'url': 'http://ok-tv.org/channels/49-2x2.html', 'img': 'http://ok-tv.org/images/2x2.png', 'title': '2x2 #5'},
{'url': 'http://ok-tv.org/channels/50-rossiya-24.html', 'img': 'http://ok-tv.org/images/ru24.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f 24 #5'},
{'url': 'http://ok-tv.org/channels/51-domashnij.html', 'img': 'http://ok-tv.org/images/domash.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc\xd0\xb0\xd1\x88\xd0\xbd\xd0\xb8\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/52-my-planeta.html', 'img': 'http://ok-tv.org/images/myplanet.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x8f \xd0\xbf\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/53-tv-3.html', 'img': 'http://ok-tv.org/images/tv3.png', 'title': '\xd0\xa2\xd0\x92-3 #5'},
{'url': 'http://ok-tv.org/channels/54-history.html', 'img': 'http://ok-tv.org/images/history.png', 'title': 'History #5'},
{'url': 'http://ok-tv.org/channels/55-illyuzion-plyus.html', 'img': 'http://ok-tv.org/images/illuzplus.png', 'title': '\xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd \xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #5'},
{'url': 'http://ok-tv.org/channels/56-russkij-illyuzion.html', 'img': 'http://ok-tv.org/images/illuzru.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\x98\xd0\xbb\xd0\xbb\xd1\x8e\xd0\xb7\xd0\xb8\xd0\xbe\xd0\xbd #5'},
{'url': 'http://ok-tv.org/channels/57-sovershenno-sekretno.html', 'img': 'http://ok-tv.org/images/sovsec.png', 'title': '\xd0\xa1\xd0\xbe\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd\xd0\xbd\xd0\xbe \xd1\x81\xd0\xb5\xd0\xba\xd1\x80\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/58-boets-tv.html', 'img': 'http://ok-tv.org/images/boec.png', 'title': '\xd0\x91\xd0\xbe\xd0\xb5\xd1\x86 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/59-istoriya.html', 'img': 'http://ok-tv.org/images/istoria.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x98\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f #5'},
{'url': 'http://ok-tv.org/channels/65-amedia-premium-hd.html', 'img': 'http://ok-tv.org/images/amediapr.png', 'title': 'Amedia Premium HD #5'},
{'url': 'http://ok-tv.org/channels/66-24-tekhno.html', 'img': 'http://ok-tv.org/images/24tehno.png', 'title': '24 \xd0\xa2\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/68-nauka-2-0.html', 'img': 'http://ok-tv.org/images/nauka.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x83\xd0\xba\xd0\xb0 2.0 #5'},
{'url': 'http://ok-tv.org/channels/69-khl.html', 'img': 'http://ok-tv.org/images/khl.png', 'title': '\xd0\x9a\xd0\xa5\xd0\x9b #5'},
{'url': 'http://ok-tv.org/channels/70-viasat-sport.html', 'img': 'http://ok-tv.org/images/viasatsport.png', 'title': 'Viasat sport #5'},
{'url': 'http://ok-tv.org/channels/71-lifenews.html', 'img': 'http://ok-tv.org/images/lifenews.png', 'title': 'Lifenews #5'},
{'url': 'http://ok-tv.org/channels/72-muz-tv.html', 'img': 'http://ok-tv.org/images/muztv.png', 'title': '\xd0\x9c\xd0\xa3\xd0\x97-\xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/73-komediya-tv.html', 'img': 'http://ok-tv.org/images/komedia.png', 'title': '\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/75-fox.html', 'img': 'http://ok-tv.org/images/foks.png', 'title': 'FOX #5'},
{'url': 'http://ok-tv.org/channels/76-fox-life.html', 'img': 'http://ok-tv.org/images/Foxlife.png', 'title': 'Fox Life #5'},
{'url': 'http://ok-tv.org/channels/77-viasat-history.html', 'img': 'http://ok-tv.org/images/vhistory.png', 'title': 'Viasat History #5'},
{'url': 'http://ok-tv.org/channels/78-amedia-1.html', 'img': 'http://ok-tv.org/images/amedia.png', 'title': 'Amedia 1 #5'},
{'url': 'http://ok-tv.org/channels/79-da-vinci-learning.html', 'img': 'http://ok-tv.org/images/davinchi.png', 'title': 'Da Vinci learning #5'},
{'url': 'http://ok-tv.org/channels/80-tv1000-comedy-hd.html', 'img': 'http://ok-tv.org/images/tv1000chd.png', 'title': 'TV1000 Comedy HD #5'},
{'url': 'http://ok-tv.org/channels/81-tv1000-premium-hd.html', 'img': 'http://ok-tv.org/images/tv1000phd.png', 'title': 'TV1000 Premium HD #5'},
{'url': 'http://ok-tv.org/channels/82-tv1000-megahit-hd.html', 'img': 'http://ok-tv.org/images/megahithd.png', 'title': 'TV1000 Megahit HD #5'},
{'url': 'http://ok-tv.org/channels/83-mtv-rossiya.html', 'img': 'http://ok-tv.org/images/mtv.png', 'title': 'MTV \xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f #5'},
{'url': 'http://ok-tv.org/channels/84-tvts.html', 'img': 'http://ok-tv.org/images/tvc.png', 'title': '\xd0\xa2\xd0\x92\xd0\xa6 #5'},
{'url': 'http://ok-tv.org/channels/85-dom-kino.html', 'img': 'http://ok-tv.org/images/domkino.png', 'title': '\xd0\x94\xd0\xbe\xd0\xbc \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/86-24-doc.html', 'img': 'http://ok-tv.org/images/24doc.png', 'title': '24_DOC #5'},
{'url': 'http://ok-tv.org/channels/87-5-kanal.html', 'img': 'http://ok-tv.org/images/5kanal.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/88-set.html', 'img': 'http://ok-tv.org/images/set.png', 'title': 'SET (Sony TV) #5'},
{'url': 'http://ok-tv.org/channels/89-travel-adventure.html', 'img': 'http://ok-tv.org/images/travel.png', 'title': 'Travel+Adventure #5'},
{'url': 'http://ok-tv.org/channels/90-avto-plyus.html', 'img': 'http://ok-tv.org/images/auto.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe \xd0\xbf\xd0\xbb\xd1\x8e\xd1\x81 #5'},
{'url': 'http://ok-tv.org/channels/91-galaxy-tv.html', 'img': 'http://ok-tv.org/images/galaxy-tv.png', 'title': 'Galaxy TV #5'},
{'url': 'http://ok-tv.org/channels/92-amedia-2.html', 'img': 'http://ok-tv.org/images/amedia-2.png', 'title': 'AMEDIA 2 #5'},
{'url': 'http://ok-tv.org/channels/93-russkij-bestseller.html', 'img': 'http://ok-tv.org/images/rus_b.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb1\xd0\xb5\xd1\x81\xd1\x82\xd1\x81\xd0\xb5\xd0\xbb\xd0\xbb\xd0\xb5\xd1\x80 #5'},
{'url': 'http://ok-tv.org/channels/94-multimaniya.html', 'img': 'http://ok-tv.org/images/multimania.png', 'title': '\xd0\x9c\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd0\xb8\xd0\xbc\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f #5'},
{'url': 'http://ok-tv.org/channels/95-kino-plyus.html', 'img': 'http://ok-tv.org/images/kinopluss.png', 'title': '\xd0\x9a\xd0\x98\xd0\x9d\xd0\x9e \xd0\x9f\xd0\x9b\xd0\xae\xd0\xa1 #5'},
{'url': 'http://ok-tv.org/channels/96-okhota-i-rybalka.html', 'img': 'http://ok-tv.org/images/ohota.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xb0 \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xb0\xd0\xbb\xd0\xba\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/97-okhotnik-i-rybolov.html', 'img': 'http://ok-tv.org/images/ohotniki.png', 'title': '\xd0\x9e\xd1\x85\xd0\xbe\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba \xd0\xb8 \xd1\x80\xd1\x8b\xd0\xb1\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/98-ctc-love.html', 'img': 'http://ok-tv.org/images/sts_love.png', 'title': '\xd0\xa1\xd0\xa2\xd0\xa1 Love #5'},
{'url': 'http://ok-tv.org/channels/99-sony-sci-fi.html', 'img': 'http://ok-tv.org/images/sonyscifi.png', 'title': 'SONY SCI-FI #5'},
{'url': 'http://ok-tv.org/channels/100-indiya-tv.html', 'img': 'http://ok-tv.org/images/india.png', 'title': '\xd0\x98\xd0\xbd\xd0\xb4\xd0\xb8\xd1\x8f \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/101-kukhnya-tv.html', 'img': 'http://ok-tv.org/images/kuhnia.png', 'title': '\xd0\x9a\xd1\x83\xd1\x85\xd0\xbd\xd1\x8f \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/102-lya-minor.html', 'img': 'http://ok-tv.org/images/liaminor.png', 'title': '\xd0\x9b\xd1\x8f-\xd0\x9c\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x80 #5'},
{'url': 'http://ok-tv.org/channels/103-muzyka-pervogo.html', 'img': 'http://ok-tv.org/images/muzikaper.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb3\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/104-nick-jr.html', 'img': 'http://ok-tv.org/images/nick-jr_2.png', 'title': 'Nick Jr #5'},
{'url': 'http://ok-tv.org/channels/105-tiji.html', 'img': 'http://ok-tv.org/images/tigi.png', 'title': 'TiJi #5'},
{'url': 'http://ok-tv.org/channels/106-evrokino.html', 'img': 'http://ok-tv.org/images/eurokino.png', 'title': '\xd0\x95\xd0\xb2\xd1\x80\xd0\xbe\xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/107-kino-tv.html', 'img': 'http://ok-tv.org/images/kinotv.png', 'title': '\xd0\x9a\xd0\xb8\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/108-park-razvlechenij.html', 'img': 'http://ok-tv.org/images/park_raz.png', 'title': '\xd0\x9f\xd0\xb0\xd1\x80\xd0\xba \xd1\x80\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xbb\xd0\xb5\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/130-eda-tv.html', 'img': 'http://ok-tv.org/images/eda.png', 'title': '\xd0\x95\xd0\xb4\xd0\xb0 \xd1\x82\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/131-8-kanal.html', 'img': 'http://ok-tv.org/images/8kanal.png', 'title': '8 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/132-rbk.html', 'img': 'http://ok-tv.org/images/rbk.png', 'title': '\xd0\xa0\xd0\x91\xd0\x9a #5'},
{'url': 'http://ok-tv.org/channels/146-kanal-yu.html', 'img': 'http://ok-tv.org/images/u.png', 'title': '\xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xae #5'},
{'url': 'http://ok-tv.org/channels/149-telekanal-futbol.html', 'img': 'http://ok-tv.org/images/futbol.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/152-hd-sport.html', 'img': 'http://ok-tv.org/images/hdsport.png', 'title': 'HD \xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 #5'},
{'url': 'http://ok-tv.org/channels/153-strashnoe-hd.html', 'img': 'http://ok-tv.org/images/strahd.jpg', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd1\x88\xd0\xbd\xd0\xbe\xd0\xb5 HD #5'},
{'url': 'http://ok-tv.org/channels/154-ostrosyuzhetnoe-hd.html', 'img': 'http://ok-tv.org/images/ostrohd.jpg', 'title': '\xd0\x9e\xd1\x81\xd1\x82\xd1\x80\xd0\xbe\xd1\x81\xd1\x8e\xd0\xb6\xd0\xb5\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 HD #5'},
{'url': 'http://ok-tv.org/channels/155-semejnoe-hd.html', 'img': 'http://ok-tv.org/images/semyiahd.jpg', 'title': '\xd0\xa1\xd0\xb5\xd0\xbc\xd0\xb5\xd0\xb9\xd0\xbd\xd0\xbe\xd0\xb5 HD #5'},
{'url': 'http://ok-tv.org/channels/157-nano-tv.html', 'img': 'http://ok-tv.org/images/nanotv.png', 'title': '\xd0\x9d\xd0\xb0\xd0\xbd\xd0\xbe \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/158-feniks-kino.html', 'img': 'http://ok-tv.org/images/fpluskino.png', 'title': '\xd0\xa4\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xba\xd1\x81 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/160-boks-tv.html', 'img': 'http://ok-tv.org/images/boxtv.png', 'title': '\xd0\x91\xd0\xbe\xd0\xba\xd1\x81 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/161-muzhskoj.html', 'img': 'http://ok-tv.org/images/muzskoy.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/166-otr.html', 'img': 'http://ok-tv.org/images/OTR.png', 'title': '\xd0\x9e\xd0\xa2\xd0\xa0 #5'},
{'url': 'http://ok-tv.org/channels/167-rtr-planeta.html', 'img': 'http://ok-tv.org/images/rtr.png', 'title': '\xd0\xa0\xd0\xa2\xd0\xa0 \xd0\x9f\xd0\xbb\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/168-avto-24.html', 'img': 'http://ok-tv.org/images/auto24.png', 'title': '\xd0\x90\xd0\xb2\xd1\x82\xd0\xbe 24 #5'},
{'url': 'http://ok-tv.org/channels/169-mgm.html', 'img': 'http://ok-tv.org/images/MGM.png', 'title': 'MGM #5'},
{'url': 'http://ok-tv.org/channels/170-russkij-roman.html', 'img': 'http://ok-tv.org/images/rus_roman.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd #5'},
{'url': 'http://ok-tv.org/channels/171-russkij-detektiv.html', 'img': 'http://ok-tv.org/images/rus_det.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/172-bumerang.html', 'img': 'http://ok-tv.org/images/bumerang.png', 'title': '\xd0\x91\xd1\x83\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb3 #5'},
{'url': 'http://ok-tv.org/channels/173-bridzh-tv.html', 'img': 'http://ok-tv.org/images/bridg.png', 'title': '\xd0\x91\xd1\x80\xd0\xb8\xd0\xb4\xd0\xb6 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/174-europa-plus-tv.html', 'img': 'http://ok-tv.org/images/europaplus.png', 'title': 'Europa Plus TV #5'},
{'url': 'http://ok-tv.org/channels/175-radost-moya.html', 'img': 'http://ok-tv.org/images/radostmoya.png', 'title': '\xd0\xa0\xd0\xb0\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c \xd0\xbc\xd0\xbe\xd1\x8f #5'},
{'url': 'http://ok-tv.org/channels/176-rossiya-kultura.html', 'img': 'http://ok-tv.org/images/rossiak.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\x9a (\xd0\x9a\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0) #5'},
{'url': 'http://ok-tv.org/channels/177-365-dnej.html', 'img': 'http://ok-tv.org/images/365dney.png', 'title': '365 \xd0\xb4\xd0\xbd\xd0\xb5\xd0\xb9 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/178-animal-planet.html', 'img': 'http://ok-tv.org/images/enimalpl.png', 'title': 'Animal Planet #5'},
{'url': 'http://ok-tv.org/channels/179-mnogo-tv.html', 'img': 'http://ok-tv.org/images/mnogo_tv.png', 'title': '\xd0\x9c\xd0\xbd\xd0\xbe\xd0\xb3\xd0\xbe \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/180-russkij-ekstrim.html', 'img': 'http://ok-tv.org/images/rusianexstreme.png', 'title': '\xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xad\xd0\xba\xd1\x81\xd1\x82\xd1\x80\xd0\xb8\xd0\xbc #5'},
{'url': 'http://ok-tv.org/channels/181-zvezda.html', 'img': 'http://ok-tv.org/images/zvezda.png', 'title': '\xd0\x97\xd0\xb2\xd0\xb5\xd0\xb7\xd0\xb4\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/182-viasat-nature.html', 'img': 'http://ok-tv.org/images/vinature.png', 'title': 'Viasat Nature #5'},
{'url': 'http://ok-tv.org/channels/183-karusel.html', 'img': 'http://ok-tv.org/images/karusel.png', 'title': '\xd0\x9a\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c #5'},
{'url': 'http://ok-tv.org/channels/184-detskij.html', 'img': 'http://ok-tv.org/images/detskiy.png', 'title': '\xd0\x94\xd0\xb5\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/185-metstso.html', 'img': 'http://ok-tv.org/images/mezzo1.png', 'title': '\xd0\x9c\xd0\xb5\xd1\x86\xd1\x86\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/186-mir.html', 'img': 'http://ok-tv.org/images/mir.png', 'title': '\xd0\x9c\xd0\xb8\xd1\x80 #5'},
{'url': 'http://ok-tv.org/channels/187-russia-today.html', 'img': 'http://ok-tv.org/images/russia_today.png', 'title': 'Russia Today #5'},
{'url': 'http://ok-tv.org/channels/188-shanson-tv.html', 'img': 'http://ok-tv.org/images/shanson.png', 'title': '\xd0\xa8\xd0\xb0\xd0\xbd\xd1\x81\xd0\xbe\xd0\xbd \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/189-english-club-tv.html', 'img': 'http://ok-tv.org/images/engl_clb.png', 'title': 'English Club TV #5'},
{'url': 'http://ok-tv.org/channels/190-rossiya-hd.html', 'img': 'http://ok-tv.org/images/russiahd.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f HD #5'},
{'url': 'http://ok-tv.org/channels/191-tlc.html', 'img': 'http://ok-tv.org/images/tlc_1.png', 'title': 'TLC #5'},
{'url': 'http://ok-tv.org/channels/192-muzhskoe-kino.html', 'img': 'http://ok-tv.org/images/muz_kino.png', 'title': '\xd0\x9c\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb5 \xd0\xba\xd0\xb8\xd0\xbd\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/193-setanta-sports.html', 'img': 'http://ok-tv.org/images/setanta.png', 'title': '\xd0\xa1\xd0\xb5\xd1\x82\xd0\xb0\xd0\xbd\xd1\x82\xd0\xb0-\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 (Setanta Sports) #5'},
{'url': 'http://ok-tv.org/channels/194-12-kanal-omsk.html', 'img': 'http://ok-tv.org/images/12omsk.png', 'title': '12 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb (\xd0\x9e\xd0\xbc\xd1\x81\xd0\xba) #5'},
{'url': 'http://ok-tv.org/channels/198-match-boets.html', 'img': 'http://ok-tv.org/images/matchboec.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x91\xd0\xbe\xd0\xb5\xd1\x86 #5'},
{'url': 'http://ok-tv.org/channels/199-match-arena.html', 'img': 'http://ok-tv.org/images/matcharen.png', 'title': '\xd0\x9c\xd0\xb0\xd1\x82\xd1\x87! \xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/200-outdoor-channel.html', 'img': 'http://ok-tv.org/images/outdoor.png', 'title': 'Outdoor Channel #5'},
{'url': 'http://ok-tv.org/channels/201-vh1.html', 'img': 'http://ok-tv.org/images/vh_1.png', 'title': 'VH1 #5'},
{'url': 'http://ok-tv.org/channels/202-gtrk-krym.html', 'img': 'http://ok-tv.org/images/krim1.png', 'title': '\xd0\x93\xd0\xa2\xd0\xa0\xd0\x9a \xd0\x9a\xd1\x80\xd1\x8b\xd0\xbc #5'},
{'url': 'http://ok-tv.org/channels/203-zdorovoe-tv.html', 'img': 'http://ok-tv.org/images/zdorovoetv.png', 'title': '\xd0\x97\xd0\xb4\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/204-retro-tv.html', 'img': 'http://ok-tv.org/images/retro.png', 'title': '\xd0\xa0\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/197-voprosy-i-otvety.html', 'img': 'http://ok-tv.org/images/voprosotvet.png', 'title': '\xd0\x92\xd0\xbe\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81\xd1\x8b \xd0\xb8 \xd0\xbe\xd1\x82\xd0\xb2\xd0\xb5\xd1\x82\xd1\x8b #5'},
{'url': 'http://ok-tv.org/channels/206-usadba.html', 'img': 'http://ok-tv.org/images/usadba.png', 'title': '\xd0\xa3\xd1\x81\xd0\xb0\xd0\xb4\xd1\x8c\xd0\xb1\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/205-rossiya-rtr.html', 'img': 'http://ok-tv.org/images/russiartr.png', 'title': '\xd0\xa0\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd1\x8f \xd0\xa0\xd0\xa2\xd0\xa0 #5'},
{'url': 'http://ok-tv.org/channels/207-zhivi.html', 'img': 'http://ok-tv.org/images/zivi.png', 'title': '\xd0\x96\xd0\xb8\xd0\xb2\xd0\xb8 #5'},
{'url': 'http://ok-tv.org/channels/208-mama.html', 'img': 'http://ok-tv.org/images/mama.png', 'title': '\xd0\x9c\xd0\x90\xd0\x9c\xd0\x90 #5'},
{'url': 'http://ok-tv.org/channels/209-life-78.html', 'img': 'http://ok-tv.org/images/life.png', 'title': 'life 78 (100 \xd1\x82\xd0\xb2) #5'},
{'url': 'http://ok-tv.org/channels/210-nostalgiya.html', 'img': 'http://ok-tv.org/images/nostalgiya.png', 'title': '\xd0\x9d\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xb3\xd0\xb8\xd1\x8f #5'},
{'url': 'http://ok-tv.org/channels/211-strana.html', 'img': 'http://ok-tv.org/images/strana1.png', 'title': '\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/212-360-gradusov.html', 'img': 'http://ok-tv.org/images/360.png', 'title': '360 \xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd1\x83\xd1\x81\xd0\xbe\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/213-tdk.html', 'img': 'http://ok-tv.org/images/tdk.png', 'title': '\xd0\xa2\xd0\x94\xd0\x9a #5'},
{'url': 'http://ok-tv.org/channels/214-tonus-tv.html', 'img': 'http://ok-tv.org/images/tonustv.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbd\xd1\x83\xd1\x81 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/215-bbc-news.html', 'img': 'http://ok-tv.org/images/bbc.png', 'title': 'BBC News #5'},
{'url': 'http://ok-tv.org/channels/216-rtvi.html', 'img': 'http://ok-tv.org/images/rtvi.png', 'title': 'RTVI #5'},
{'url': 'http://ok-tv.org/channels/223-sarafan-tv.html', 'img': 'http://ok-tv.org/images/sarafan.png', 'title': '\xd0\xa1\xd0\xb0\xd1\x80\xd0\xb0\xd1\x84\xd0\xb0\xd0\xbd \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/224-yumor-tv.html', 'img': 'http://ok-tv.org/images/umortv.png', 'title': '\xd0\xae\xd0\xbc\xd0\xbe\xd1\x80 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/225-ryzhij.html', 'img': 'http://ok-tv.org/images/riziy.png', 'title': '\xd0\xa0\xd1\x8b\xd0\xb6\xd0\xb8\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/228-nashe-hd.html', 'img': 'http://ok-tv.org/images/nashehd.png', 'title': '\xd0\x9d\xd0\xb0\xd1\x88\xd0\xb5 HD #5'},
{'url': 'http://ok-tv.org/channels/229-nat-geo-wild.html', 'img': 'http://ok-tv.org/images/natgeowild.png', 'title': 'NAT GEO WILD #5'},
{'url': 'http://ok-tv.org/channels/237-morskoj.html', 'img': 'http://ok-tv.org/images/morskoy.png', 'title': '\xd0\x9c\xd0\xbe\xd1\x80\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/238-amc.html', 'img': 'http://ok-tv.org/images/amc1.png', 'title': 'AMC #5'},
{'url': 'http://ok-tv.org/channels/22-1-1.html', 'img': 'http://ok-tv.org/images/button_1i1.png', 'title': '1+1 #5'},
{'url': 'http://ok-tv.org/channels/23-2-2.html', 'img': 'http://ok-tv.org/images/button_2_2.png', 'title': '2+2 #5'},
{'url': 'http://ok-tv.org/channels/24-stb.html', 'img': 'http://ok-tv.org/images/stb.png', 'title': '\xd0\xa1\xd0\xa2\xd0\x91 #5'},
{'url': 'http://ok-tv.org/channels/32-novyj-kanal.html', 'img': 'http://ok-tv.org/images/button_novij.png', 'title': '\xd0\x9d\xd0\xbe\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/33-inter.html', 'img': 'http://ok-tv.org/images/button_inter.png', 'title': '\xd0\x98\xd0\xbd\xd1\x82\xd0\xb5\xd1\x80 #5'},
{'url': 'http://ok-tv.org/channels/34-ictv.html', 'img': 'http://ok-tv.org/images/button_ictv.png', 'title': 'ICTV #5'},
{'url': 'http://ok-tv.org/channels/35-trk-ukraina.html', 'img': 'http://ok-tv.org/images/button_ukraina.png', 'title': '\xd0\xa2\xd0\xa0\xd0\x9a \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/36-ntn-ukraina.html', 'img': 'http://ok-tv.org/images/button_ntn.png', 'title': '\xd0\x9d\xd0\xa2\xd0\x9d (\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0) #5'},
{'url': 'http://ok-tv.org/channels/37-mega.html', 'img': 'http://ok-tv.org/images/button_mega.png', 'title': '\xd0\x9c\xd0\xb5\xd0\xb3\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/38-qtv.html', 'img': 'http://ok-tv.org/images/button_qtv.png', 'title': 'QTV #5'},
{'url': 'http://ok-tv.org/channels/39-tet.html', 'img': 'http://ok-tv.org/images/tet.png', 'title': '\xd0\xa2\xd0\x95\xd0\xa2 #5'},
{'url': 'http://ok-tv.org/channels/60-pervyj-natsionalnyj.html', 'img': 'http://ok-tv.org/images/ut1.png', 'title': '\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 \xd0\xbd\xd0\xb0\xd1\x86\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/61-futbol-1.html', 'img': 'http://ok-tv.org/images/ukrfoot1.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 1 #5'},
{'url': 'http://ok-tv.org/channels/62-futbol-2.html', 'img': 'http://ok-tv.org/images/ukrfoot2.png', 'title': '\xd0\xa4\xd1\x83\xd1\x82\xd0\xb1\xd0\xbe\xd0\xbb 2 #5'},
{'url': 'http://ok-tv.org/channels/63-k1.html', 'img': 'http://ok-tv.org/images/k1.png', 'title': '\xd0\x9a1 #5'},
{'url': 'http://ok-tv.org/channels/64-k2.html', 'img': 'http://ok-tv.org/images/k2.png', 'title': '\xd0\x9a2 #5'},
{'url': 'http://ok-tv.org/channels/67-112-kanal.html', 'img': 'http://ok-tv.org/images/112ua.png', 'title': '112 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb #5'},
{'url': 'http://ok-tv.org/channels/74-5-kanal-ukraina.html', 'img': 'http://ok-tv.org/images/5_ukraine.png', 'title': '5 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/124-news-one.html', 'img': 'http://ok-tv.org/images/newsone.png', 'title': 'News One #5'},
{'url': 'http://ok-tv.org/channels/125-24-ukraina.html', 'img': 'http://ok-tv.org/images/24ua.png', 'title': '24 \xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/126-espreso-tv.html', 'img': 'http://ok-tv.org/images/expressotv.png', 'title': '\xd0\x95\xd1\x81\xd0\xbf\xd1\x80\xd0\xb5\xd1\x81\xd0\xbe \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/127-gromadske-tv.html', 'img': 'http://ok-tv.org/images/gromads.png', 'title': '\xd0\x93\xd1\x80\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xb4\xd1\x81\xd1\x8c\xd0\xba\xd0\xb5 \xd1\x82\xd0\xb2 #5'},
{'url': 'http://ok-tv.org/channels/128-11-kanal-dnepropetrovsk.html', 'img': 'http://ok-tv.org/images/11_kanal.png', 'title': '11 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb (\xd0\x94\xd0\xbd\xd0\xb5\xd0\xbf\xd1\x80\xd0\xbe\xd0\xbf\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba) #5'},
{'url': 'http://ok-tv.org/channels/129-tonis.html', 'img': 'http://ok-tv.org/images/tonis.png', 'title': '\xd0\xa2\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x81 #5'},
{'url': 'http://ok-tv.org/channels/138-nlo-tv.html', 'img': 'http://ok-tv.org/images/nlo.png', 'title': '\xd0\x9d\xd0\x9b\xd0\x9e \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/147-sport-1-ukraina.html', 'img': 'http://ok-tv.org/images/sport1ua.png', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 1 (\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0) #5'},
{'url': 'http://ok-tv.org/channels/148-sport-2-ukraina.html', 'img': 'http://ok-tv.org/images/sport2ua.png', 'title': '\xd0\xa1\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82 2 (\xd0\xa3\xd0\xba\xd1\x80\xd0\xb0\xd0\xb8\xd0\xbd\xd0\xb0) #5'},
{'url': 'http://ok-tv.org/channels/150-telekanal-gamma.html', 'img': 'http://ok-tv.org/images/gamma.png', 'title': '\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb \xd0\x93\xd0\xb0\xd0\xbc\xd0\xbc\xd0\xb0 #5'},
{'url': 'http://ok-tv.org/channels/151-gumor-tv.html', 'img': 'http://ok-tv.org/images/gumorr.png', 'title': '\xd0\x93\xd1\x83\xd0\xbc\xd0\xbe\xd1\x80 \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/156-ua-pervyj.html', 'img': 'http://ok-tv.org/images/uapershiy.jpg', 'title': 'UA \xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd1\x8b\xd0\xb9 #5'},
{'url': 'http://ok-tv.org/channels/162-plyusplyus.html', 'img': 'http://ok-tv.org/images/pluspluss.png', 'title': '\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81\xd0\x9f\xd0\xbb\xd1\x8e\xd1\x81 #5'},
{'url': 'http://ok-tv.org/channels/163-bigudi.html', 'img': 'http://ok-tv.org/images/bigudii.png', 'title': '\xd0\x91\xd0\xb8\xd0\xb3\xd1\x83\xd0\xb4\xd0\xb8 #5'},
{'url': 'http://ok-tv.org/channels/164-m1.html', 'img': 'http://ok-tv.org/images/m1.png', 'title': '\xd0\x9c1 #5'},
{'url': 'http://ok-tv.org/channels/165-malyatko.html', 'img': 'http://ok-tv.org/images/malyatko.png', 'title': '\xd0\x9c\xd0\xb0\xd0\xbb\xd1\x8f\xd1\x82\xd0\xba\xd0\xbe #5'},
{'url': 'http://ok-tv.org/channels/195-piksel.html', 'img': 'http://ok-tv.org/images/piksel.png', 'title': '\xd0\x9f\xd0\xb8\xd0\xba\xd1\x81\xd0\xb5\xd0\xbb\xd1\x8c \xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/196-m2.html', 'img': 'http://ok-tv.org/images/m2.png', 'title': '\xd0\x9c2 #5'},
{'url': 'http://ok-tv.org/channels/239-vtv.html', 'img': 'http://ok-tv.org/images/vtvtv.png', 'title': '\xd0\x92\xd0\xa2\xd0\x92 #5'},
{'url': 'http://ok-tv.org/channels/240-ont.html', 'img': 'http://ok-tv.org/images/ont.png', 'title': '\xd0\x9e\xd0\x9d\xd0\xa2 #5'},
{'url': 'http://ok-tv.org/channels/241-belarus-1.html', 'img': 'http://ok-tv.org/images/belarus1.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 1 #5'},
{'url': 'http://ok-tv.org/channels/242-belarus-2.html', 'img': 'http://ok-tv.org/images/Belarus2.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 2 #5'},
{'url': 'http://ok-tv.org/channels/243-belarus-3.html', 'img': 'http://ok-tv.org/images/belarus3.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 3 #5'},
{'url': 'http://ok-tv.org/channels/244-belarus-5.html', 'img': 'http://ok-tv.org/images/belarus5.png', 'title': '\xd0\x91\xd0\xb5\xd0\xbb\xd0\xb0\xd1\x80\xd1\x83\xd1\x81\xd1\x8c 5 #5'},
]
